version: 2.1

orbs:
  gusto: gusto/gusto@0.0.13

jobs:
  test:
    docker:
      - image: circleci/ruby:2.7-node
    steps:
      - gusto/yarn-install
      - run: yarn lint
      - run: yarn test
  release:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - gusto/yarn-install
      # Run optional required steps before releasing
      # - run: npm run build-script
      - run: npx semantic-release

workflows:
  version: 2
  main:
    jobs:
      - test
      - release:
          filters:
            branches:
              only: master
          requires:
            - test
